- hosts: all
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes



    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes